server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: shivam.aj.sharma
    password: abc@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

secret:
  jwt: MySecretKey12345

openai:
  api:
    key: gsk_5rHEOfYx81XlFtHCWGdyb3FYOk4MrxlGelPsyNDD0invnPDy

info:
  app:
    name: Learning platform backend services
    version: v1

management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always

anthropic:
  api:
    key: sk-ant-xxx